version: "3.8"

services:
  app-bash:
    image: docker-secrets-app-bash:latest
    container_name: docker-secrets-app-bash
    secrets: 
      - file_login
      - file_password
    build:
      context: ./app-bash
      dockerfile: Dockerfile

  app-python:
    image: docker-secrets-app-python:latest
    container_name: docker-secrets-app-python
    build:
      context: ./app-python
      dockerfile: Dockerfile
    env_file:
      - .secrets.env
    environment:
      - ENV_LOGIN=my_env_login
      - ENV_PASSWORD=my_env_password
    secrets: 
      - file_login
      - file_password
    ports:
      - 8181:8181

secrets:
  file_login:
    file: ./file-login.txt
  file_password:
    file: ./file-password.txt
  external_login:
    external: true
  external_password:
    external: true
